### ISSUE TITLE
Solo Enabler adds Firewall entries, but is not blocking matchmaking.

### ISSUE THREAD

**Issue by Equ1no0x** [DrNoLife/Destiny-2-Solo-Enabler#15]
The issue started around 2-3 days ago. I had not used Solo Enabler for around a week more or less and that last time it was working perfectly.

![image](https://user-images.githubusercontent.com/77862920/117336499-7e58c000-ae59-11eb-9651-880a49411bfd.png)
![image](https://user-images.githubusercontent.com/77862920/117338742-28394c00-ae5c-11eb-93b3-6e0733663f41.png)

**Comment by Equ1no0x** [comment]
Seems to have been resolved by returning Firewall settings to Restore Defaults or just clicking on Recommended Settings. Will continue checking if it works with no issues.

**Comment by DrNoLife** [comment]
Glad you got it sorted out.
