### ISSUE TITLE
Porting to other games

### ISSUE THREAD

**Issue by WitheringRetort** [DrNoLife/Destiny-2-Solo-Enabler#18]
I have been using this to wondrous effect for about 6 months now, but I want to get the same effect in other games, mostly Escape From Tarkov. Is it possible to transpose this to take effect with EFT or other games, and how would that be done?

Thanks!
C.B.

**Comment by Jasontyler221** [comment]
> I have been using this to wondrous effect for about 6 months now, but I want to get the same effect in other games, mostly Escape From Tarkov. Is it possible to transpose this to take effect with EFT or other games, and how would that be done?
> 
> Thanks!
> C.B.

Actually, i'm pretty sure that is a bannable offense in Tarkov as the game is built around PvP, however, there are server emulators from dedicated modders made for specific versions, they're known as JET (JustEmuTarkov) and SPT-AKI (SPTarkov)

Both of these emulate the game server backend on your machine, allowing you to even add mods to your server and configure its settings. 

If you want the most mods, i recommend using SPT-AKI, and using their client downgrade tool to downgrade the client files to a compatible version with their server. SPT-AKI requires the game files of a purchased copy, though i assume you already have one, just make sure you copy the files to a different directory than your live game and mod that new directory, else you'll get banned on the live game.
https://mods.sp-tarkov.com/files/

**Comment by DrNoLife** [comment]
Hey, glad to hear you like it.

However, as Jason said before me, it would not surprise me if one would risk a ban if used in Tarkov. This is allowed in Destiny, due to the nature of the game (it being a PvE game). 

In reality I don't even know if it's possible, but I would not encourage trying it.
