### ISSUE TITLE
wondering if BE will ban players who use this tool

### ISSUE THREAD

**Issue by baobobby** [DrNoLife/Destiny-2-Solo-Enabler#19]

**Comment by delsinz** [comment]
I was wondering the same thing. Has anyone tried using it with BattlEye running?

**Comment by AndyGFX** [comment]
Yes. Works. ;)

**Comment by BSingels** [comment]
> Yes. Works. ;)

I don't doubt that it works. The question is does Battle Eye see it as some sort of hack and get you banned ?

**Comment by AndyGFX** [comment]
> > Yes. Works. ;)
> 
> I don't doubt that it works. The question is does Battle Eye see it as some sort of hack and get you banned ?

OK. Actualy I'm not baned - tried in vanguard strike for example and in tower too (because I forgot switch it off, when strike ends :) ).

**Comment by baobobby** [comment]
> > > Yes. Works. ;)
> > 
> > 
> > I don't doubt that it works. The question is does Battle Eye see it as some sort of hack and get you banned ?
> 
> OK. Actualy I'm not baned - tried in vanguard strike for example and in tower too (because I forgot switch it off, when strike ends :) ).

well, thanks for your report, it is glad to see some positiv feedbacks, but we better wait a few days, you know, just to make sure that this tool 100% safe after BE installed.

**Comment by delsinz** [comment]
> > > > Yes. Works. ;)
> > > 
> > > 
> > > I don't doubt that it works. The question is does Battle Eye see it as some sort of hack and get you banned ?
> > 
> > 
> > OK. Actualy I'm not baned - tried in vanguard strike for example and in tower too (because I forgot switch it off, when strike ends :) ).
> 
> well, thanks for your report, it is glad to see some positiv feedbacks, but we better wait a few days, you know, just to make sure that this tool 100% safe after BE installed.

Thinking the same thing. BE auto ban is not enabled right now. Every ban is still manually reviewed. So we never know what's going to happen after they enable auto ban.

**Comment by inferno-prime** [comment]
I was wondering if this is safe to use as well. And should I go to Bungie's forum and ask because in my opinion, I don't really see this as violating anything?

**Comment by DrNoLife** [comment]
Unless Bungie has changed their stance on this subject, then one should not get banned from using it. 
I've also yet to receive a single complaint about anyone being banned due to usage of the program, and I myself have used it during this current season.

A reminder, the program does not interact with the game at all, it merely creates some firewall rules. These rules basically makes your PC deny all traffic coming from / to certain ports (and thus blocking the match making traffic).

**Comment by coledeb** [comment]
Used this multiple times during the season, no issues with bans or with Battlenet at all.

**Comment by delsinz** [comment]
> > > > > Yes. Works. ;)
> > > > 
> > > > 
> > > > I don't doubt that it works. The question is does Battle Eye see it as some sort of hack and get you banned ?
> > > 
> > > 
> > > OK. Actualy I'm not baned - tried in vanguard strike for example and in tower too (because I forgot switch it off, when strike ends :) ).
> > 
> > 
> > well, thanks for your report, it is glad to see some positiv feedbacks, but we better wait a few days, you know, just to make sure that this tool 100% safe after BE installed.
> 
> Thinking the same thing. BE auto ban is not enabled right now. Every ban is still manually reviewed. So we never know what's going to happen after they enable auto ban.

Been using this for about two weeks after BE auto ban was enabled. No issue so far. So I guess BE doesn't view changing firewall rules as intrusive for now.
