### ISSUE TITLE
NOT Working

### ISSUE THREAD

**Issue by jokerUAE** [DrNoLife/Destiny-2-Solo-Enabler#20]
hi 

the App not working with me, when I press ENABLE on the Orbit 💫. nothing happening the matchmaking is work and the game put other players with me.

the Windows  is 10 pro
the Firewall not working

**Comment by PercyJdd** [comment]
Im guessing this doesn't work anymore rip d2

**Comment by DrNoLife** [comment]
> Im guessing this doesn't work anymore rip d2

Nah it still works. My guess is the other guy simply forgot he has some other program which handles Firewall stuff for him.

**Comment by dermaxem** [comment]
same here. the tool was working well about 1 week ago, but today theres no blocking anymore. at a 2nd start of the Programm it suddenly works - no other changes. just end and restart it.
strange....
