### ISSUE TITLE
How to ensure that DLLs don't have malicious initialization code?

### ISSUE THREAD

**Issue by cassiusvm** [DrNoLife/Destiny-2-Solo-Enabler#24]
How to ensure that DLLs don't have malicious initialization code since we don't have access to their source code?

Reference: https://stackoverflow.com/questions/17126779/generating-initialization-code-for-dll

**Comment by andrewpong** [comment]
You can look at the code yourself, @cassiusvm, unless I'm missing something. I did a quick glance through the project and didn't see any mystery DLLs or obfuscated code.

The [source code is available](git@github.com:DrNoLife/Destiny-2-Solo-Enabler.git) for you to compile yourself - [pic for proof](https://user-images.githubusercontent.com/3084944/150466512-beca702a-df50-46f5-a8c3-e4c0acba86b5.png)!!
