### ISSUE TITLE
Does this application still work?

### ISSUE THREAD

**Issue by arjunsrinivasan1997** [DrNoLife/Destiny-2-Solo-Enabler#25]
Hello,
I have recently tried to use this app to play solo in D2, and when I was trying to solo some nightmare hunts, I kept being loaded into ones with other people. I saw the last update saying it worked was in Nov 2020, so does this still work and is this still a viable method to have solo mode in D2?

**Comment by Percdye7** [comment]
Currently this one doesn't work anymore. But there is a PowerShell script that is working.

Either use Google, look on Discord. I have it on GH aswell.

**Comment by DrNoLife** [comment]
Yes, the program does still work. 
I tested it roughly a week ago, and tested it once again less than an hour ago. Worked with no issues.
