### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gurusz1** [DrNoLife/Destiny-2-Solo-Enabler#26]
I am in orbit, i launch the program, i land on the tower, guardians everywhere

**Comment by HLAmaral** [comment]
I'm in orbit, lauch the app as "Administrator", choose "SOLO PLAY ON", star a Vanguard Ops Playlist, other guardians with me... :/

**Comment by DrNoLife** [comment]
I can't reproduce. For me, the program works as it always has.
No changes has been made to the program, and as far as I can see, no changes has been made from Bungie's end either in regards to match making.

**Comment by BLTplayz** [comment]
@HLAmaral @gurusz1 If you are still encountering issues, I recommend attempting the fix in [this ](https://github.com/DrNoLife/Destiny-2-Solo-Enabler/issues/28#issuecomment-1236405479)issue thread!
