### ISSUE TITLE
Can you manually deactivate the script

### ISSUE THREAD

**Issue by nebulaxarimp4** [DrNoLife/Destiny-2-Solo-Enabler#27]
I've run the old version and turned the solo mode on but then the program crashes when I try to turn it off. More recent versions don't work at all.

**Comment by DrNoLife** [comment]
What the program does is create firewall rules. If you believe these to be persisting even after closing the program, then you can check out your firewall settings. In there, you can look for some rules named "Destiny 2 - Solo-Enabler" - if you find any, right click on them and delete them.
