### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by Satrrrn** [DrNoLife/Destiny-2-Solo-Enabler#28]
I downloaded this programs latest version and was followed all the steps to keep the program rather than it auto deleting itself but when I turn it on while in orbit I'm still put queued in with other people. No notification saying the services are unavailable either. Can you help me pls?

**Comment by BLTplayz** [comment]
I had the same issue and it took some firewall modifications to fix. Open the control panel and go to System and Security, click on Windows Defender Firewall, and on the left click 'View Advanced Settings. Choose 'Inbound Rules' and scroll until you see the rule(s) named 'Destiny 2' (there may be multiple, I had 8). 
These rules simply allowed all ports to be forwarded past the firewall. This also meant it would override the solo-enabler rules. I simply deleted all the 'Destiny 2' rules and it fixed all my problems. Hope this fixes your problem/anyone else that is having a similar issue! 

Note: Removing firewall rules can present security issues in specific cases but I firmly believe this is harmless as it only is a rule applied to Destiny 2.exe!
