### ISSUE TITLE
Still loading into matched strikes

### ISSUE THREAD

**Issue by AphelionRage** [DrNoLife/Destiny-2-Solo-Enabler#29]
I had everything disabled when I downloaded your file, as well as when I launch it. But I'm still getting matched with people and there is no service interruption message from steam indicating some features wont work. I believe they may have patched something since your last video showing the program working.

**Comment by noto-rious** [comment]
Seems to be working fine for me.

**Comment by arjunsrinivasan1997** [comment]
I am also seeing this issue where I'm still getting matched with people as well. I'm seeing the firewall rules pop up, but still getting matched with people.

![image](https://user-images.githubusercontent.com/25167567/166864338-bc88eca3-a10b-4471-8359-93d0c3fc4602.png)
![image](https://user-images.githubusercontent.com/25167567/166864361-27d4b696-ea34-4b9e-a622-2ba458958fd3.png)

**Comment by BLTplayz** [comment]
I had the same issue, if you scroll down in the Inbound Rules there should be two rules simply named 'Destiny 2' (there may be more, I had 8). The rule simply allowed all ports to be forwarded. This also meant it would override the solo-enabler rules. I simply deleted the 'Destiny 2' rules and it fixed all my problems. Hope this fixes your problem/anyone else that is having a similar issue!

**Comment by arjunsrinivasan1997** [comment]
@BLTplayz thanks for the tip, this worked for me.

**Comment by heroicxidiot** [comment]
I still can't get it to work for me. I've deleted the inbound rules for D2 on my defender and through my 3rd party firewall. The solo enablers are up from what I see. I'm stuck on what could possibly be the problem

**Comment by MajorMalarky** [comment]
Is this application using any Powershell by chance?  I got it to work after going in and setting my execution policy to unrestricted.  It could be something you may want to throw in the application "set-executionpolicy bypass".

**Comment by DrNoLife** [comment]
> Is this application using any Powershell by chance? I got it to work after going in and setting my execution policy to unrestricted. It could be something you may want to throw in the application "set-executionpolicy bypass".

No, the program itself is not using any powershell. Calls into a wrapper for a native library which allows me to make changes to the Windows firewall. But I'll add a link to your comment in the readme.

**Comment by pasisavolainen** [comment]
I ran into this issue (firewall rules appear but don't seem to work). For me the issue was that whole Windows Defender Firewall was turned off (this was workaround for some ubisoft uplay sertificate issue). After turning it back on, everything worked, long connection time (as it's supposed to be with not finding peers) and then it loads me single into strike.

![image](https://user-images.githubusercontent.com/6162135/210157189-0481dbe5-6ddd-4968-b98d-deeef9592799.png)

**Comment by DrNoLife** [comment]
Closing this, as it seems like the fix was removing some other firewall rules that overwrote the ones from D2SE.

A fix for this has been implemented in the latest release. 

https://github.com/DrNoLife/Destiny-2-Solo-Enabler/releases/tag/3.1
