### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by 02taeb** [DrNoLife/Destiny-2-Solo-Enabler#30]
Toggleable Always on top

**Comment by DrNoLife** [comment]
I'll give it a go. Can't give an ETA for it, since real life is keeping me a bit busy right now.

But I'll let you know whenever an update comes around regarding this.

**Comment by DrNoLife** [comment]
@02taeb as suggested, I've added an option to enable "always on top" functionality.
You can get the latest release here: https://github.com/DrNoLife/Destiny-2-Solo-Enabler/releases/tag/2.4

**Comment by 02taeb** [comment]
Sweet! Cheers!
