### ISSUE TITLE
Possible IP Whitelisting?

### ISSUE THREAD

**Issue by BlackjackMKV** [DrNoLife/Destiny-2-Solo-Enabler#34]
Heya! I was wondering if there was a way to make it so that you could whitelist certain IPs. I haven't tried this myself yet, but, provided it works the same way as GTA V(which it at least seems to with my limited knowledge), it should be as easy as allowing IPs to be added to the Windows Firewall 'scope' section for the rules. In short, I'm hoping you could make it so only certain IPs would be able to connect to you. That way, if I have, for example, just one friend and we want to just hang out in a private open world area or playlist strikes or what have you, we'd be able to. Is this potentially possible?

Example of one of the tools for GTA V that do the same thing here. I don't know how applicable the code is, but I *believe* that same method of just adding the IPs to the inbound/outbound rules' scope should hopefully work:
[https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby](https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby)

**Comment by BLTplayz** [comment]
If I understand you correctly, I do not think adding this would be a good idea as it might qualify as network manipulation. It would be a great feature but if it functions as you describe, it could be used maliciously in PVP matchmaking. 

For more info, under the [Destiny Account Restrictions and Banning Policies](https://help.bungie.net/hc/en-us/articles/360049517431) listed under the Win Trading section:
"...includes but is not limited to manipulating matchmaking by any means to force-match with specific opponents..."

**Comment by DrNoLife** [comment]
This won't be possible.

1. This program does not handle match making for you. Steam's services do that. This program makes sure the game can't communicate with those services, thus making the game default to creating a single instance of the gamemode queing for.
2. Even if it were possibly: due to the reason outlined by @BLTplayz it would not be something that I'd be adding.
