### ISSUE TITLE
Xbox game pass version?

### ISSUE THREAD

**Issue by rlewkowicz** [DrNoLife/Destiny-2-Solo-Enabler#35]
This works in the current state, due to the way they use steam sockets. I doubt the gamepass version does. Do you have any insight on this as I go download it to find out? I'm writing my own utilities and it could save me time if you already have the answer

**Comment by DrNoLife** [comment]
I have no knowledge of how the Xbox version of the game handles matchmaking, nor any knowledge of how the Xbox itself handles firewall policies, but I highly doubt it's running the default Windows firewall. 

Whether or not it's possible, I can't say. But if you can figure out which service is handling the matchmaking, and which ports are being used, then see if you can somehow block those from being used by your client. That'd be my best guess.

But good luck to you with the project! 😄

**Comment by rlewkowicz** [comment]
Yeah, it was a dead end. Interestingly enough, it also uses steam sockets.
