### ISSUE TITLE
cant play matchmaking anymore after my friend turned it on with me in the fireteam. 

### ISSUE THREAD

**Issue by Kanadium** [DrNoLife/Destiny-2-Solo-Enabler#36]
as i stated i cant play multiplayer anything anymore. tried resetting my firewall to factory settings (didn't work) went in and specifically enabled the D2 app as well as steam . still to no avail though. any ideas?

**Comment by DrNoLife** [comment]
That's not how the program works.

Imagine a scenario where you and your teammate is playing. Suddenly he lags out, looses connection. Then after that, you are no longer able to use matchmaking anymore.

That doesn't make sense, and D2SE does something very similar to the scenario described above. Therefore, all I can say is: It's a problem on your end, the program cannot interfere in others matchmaking experience like that.
