### ISSUE TITLE
Is this Steam exclusive?

### ISSUE THREAD

**Issue by Trae132** [DrNoLife/Destiny-2-Solo-Enabler#43]
I saw mentioned it blocks ports used by steam, if Im using epic games version will this work?  I love the game so far but cant stand having to que with randoms who race through as fast as possible.  I want to take my time and enjoy my first runs or perhaps do bounties or something, this is insane that you had to come up with something like this but I surte hope i can get it working.

**Comment by BLTplayz** [comment]
It should work regardless of platform on PC. While I am not able to test this at the moment, Destiny.exe should use the same ports on any platform. 

If it is not working, check the troubleshooting section. You'll see a few issue threads linked there for more in-depth instructions. Feel free to put updates and questions in this thread to help improve troubleshooting for future cases!

**Comment by Geist4587** [comment]
Please please watch my videos I don't want any followers I need the help of the masses Bungie the Destiny 2 developers have been hacking my HP Omen PC for over a year I've asked for help everywhere Facebook Instagram YouTube and Twitter put me in incognito so the truth  It doesn't come out, the sad thing is I haven't even paid it off completely and they don't stop hacking me, please distribute my videos, help me, I've been fighting Bungie for a long time with depression.  https://youtube.com/shorts/feRDkmBOyA4?si=GoWKFnyxqIi-eWkg
