### ISSUE TITLE
Stuck in Solo

### ISSUE THREAD

**Issue by soloexo** [DrNoLife/Destiny-2-Solo-Enabler#50]
**Hey there!** I've encountered a similar issue like I have atm, but not with this specific program. It was a while back and the problem occurred with the DIM actions in the Elgato Steam Deck.. in particular its SOLO MODE. I was quite frustrated trying to resolve it! Anyway, the day before yesterday, I realized that I couldn't see anyone in the tower. I usually play solo about 98% of the time, so this might have been going on for a while. Now, I needed to do some co-op activities, but I need help to connect. _I have to admit that I have a bad habit of forgetting to turn it off before I quit playing_. I don't know if that caused the issue. Another thing that happened was I was online before a Bungie Update, and I was doing something else (I have ADHD) while in orbit. I didn't get kicked, and I was the only person on the server. I could land anywhere, but it said _"You are not connected to the game world."_ I quickly closed the game, and since then, it hasn't been connecting to multiplayer. I wonder if this information helps. _
_### I've tried everything from opening the app in orbit, turning it off, checking, turning it back on, turning it off again, checking, shutting down everything, rebooting, checking, even reinstalling your app, checking.. rolling back windows.. used a recover checkpoint... As of rn I'm considering reinstalling the game, but I'm hoping to find a better fix if anyone else has experienced this issue.__ 
Secret time..I can't emphasize enough how much stress I went through last time this happened, only to realize all I needed to do was reinstall the DIM app, enable it in-game, and then turn it off. LOL.. (I literally bought a new copy of Windows trying to fix it) So yeah.. this time, I'm going to the source and hoping for a kind drop of wisdom for my ignorant ass.

By the way, huge thanks for this app! I believe I donated if there was an option.. if there wasn't please let me know how I can throw you some love. I mean...I use it every day... seriously... You're awesome!

**Comment by soloexo** [comment]
Yo..

I fixed it. It was that old app in my Steam deck. I have no idea how it got enabled. It was an odd hot-key press, like maybe moving the deck around and touching it. Either way, I'm super sorry for the waste of time and any brain cells I killed. And again, you're a legend in my book!

**Comment by derfurkan** [comment]
> Yo..
> 
> I fixed it. It was that old app in my Steam deck. I have no idea how it got enabled. It was an odd hot-key press, like maybe moving the deck around and touching it. Either way, I'm super sorry for the waste of time and any brain cells I killed. And again, you're a legend in my book!

When you fixed it then close this issue bro...

**Comment by soloexo** [comment]
thank you, sorry I didnt realize I needed to close this out. Hope I didn't cause any issues.
