### ISSUE TITLE
An UI suggestion

### ISSUE THREAD

**Issue by Troy-T** [DrNoLife/Destiny-2-Solo-Enabler#9]
I thought I's make a comment about the UI since the from the description you seemed to put emphasis on it.

It's not necessarily clear if the the solo play is on or off. When looking at the program it could either be a an indicator that shows what state your currently in or a button that switches to the state shown.

![image](https://user-images.githubusercontent.com/47111151/103297077-71c9e400-49ef-11eb-90fe-32824c1e81b9.png)
Take this screen for example. It could be telling me that solo play is off _or_ it could be telling me I need to push the button to turn solo play off.

My suggestion would be to have an indicator separate from the button that tells you if solo play is enabled.

**Comment by DrNoLife** [comment]
Had that earlier, however I do not believe it's needed. The current design is clear enough, as it says in text the current status is "OFF", and the button itself is muted. 
By using the program, you will see the button changes color to a bright yellow one, indicating the program is on. As soon as you've done this once, there will not be any misunderstandings whether or not it's turned on or not.
